Repository usabilla/php-docker-template, pull requests merged in 2019-11, with the labels that each got.

#140 Move composer to -dev images
  Dockerfile-cli
  Dockerfile-fpm
  test/container/php/test_composer.py
Labels: Refactoring

#139 Remove fastcgi_split_path_info from nginx config
  src/http/nginx/conf/php-fpm/vhost.conf.template
Labels: Refactoring

#141 Use PHP 7.3 and Alpine 3.10 during tests
  test/functional/web/index.php
  test/inheritance/Dockerfile
Labels: Refactoring

#142 Replace PHP 7.4 RC with PHP 7.4 final
  Makefile
Labels: Feature

#144 Revert: Move composer to -dev images
  Dockerfile-cli
  Dockerfile-fpm
  test/container/php/test_composer.py
Labels: Bug
