Repository usabilla/php-docker-template, pull requests merged in 2019-04, with the labels that each got.

#90 Doc/improve readability
  README.md
Labels: Documentation

#92 Feature/enable default php ini config
  Dockerfile-cli
  Dockerfile-fpm
  Makefile
  README.md
  src/php/utils/docker/docker-php-dev-mode
  test-fpm.sh
  test/container/php/test_config.py
  test/container/php/test_dev_config.py
  test/container/php/test_extensions.py
  test/container/php/test_helper_scripts.py
Labels: Documentation, Feature

#97 Nginx logging
  .circleci/config.yml
  Makefile
  src/http/nginx/conf/nginx.conf.template
  test-http-e2e.sh
  test/e2e/conftest.py
  test/e2e/test_nginx_entrypoint.py
  test/e2e/test_nginx_logs.py
Labels: Feature

#99 Static file Prometheus exporter
  .circleci/config.yml
  Dockerfile-http
  Makefile
  README.md
  build-nginx.sh
  build-prometheus-exporter-file.sh
  src/http/nginx/conf/main/location.d-available/cors.conf
  src/http/nginx/conf/main/location.d-enabled/.gitkeep
  src/http/nginx/conf/main/nginx.conf.template
  src/http/nginx/conf/php-fpm/vhost.conf.template
  src/http/nginx/conf/prometheus-exporter-file/vhost.conf.template
  test-prometheus-exporter-file-e2e.sh
  test/e2e/test_prometheus_exporter_file.py
Labels: Feature
