Repository usabilla/php-docker-template, pull requests merged in 2020-10, with the labels that each got.

#159 Use Xdebug stable channel
  src/php/utils/docker/docker-php-dev-mode
Labels: CI

#161 Add `--1` flag to Composer's installer
  src/php/utils/install-composer
Labels: Dependencies

#162 Update PHP and Alpines version in README
  README.md
Labels: Documentation
