Repository usabilla/php-docker-template, pull requests merged in 2021-07, with the labels that each got.

#175 Add a sleep before running prometheus exporter e2e tests
  test/e2e/test_prometheus_exporter_file.py
Labels: Bug

#173 Add PHP 7.1 image
  .github/workflows/ci.yml
  Dockerfile-cli
  Dockerfile-fpm
  src/gpg/528995BFEDFBA7191D46839EF9BA0ADA31CBD89E.asc
  src/gpg/A917B1ECDA84AEC2B568FED6F50ABC807BD5DCD0.asc
  src/php/utils/docker/docker-php-dev-mode
Labels: Feature

#177 Build the latest version of Alpine
  .github/workflows/ci.yml
Labels: Dependencies

#176 Update `realestate-com-au/shush` to `v1.5.0`
  src/php/utils/install-shush
Labels: Dependencies

#179 Start building PHP 8.0 images
  .github/workflows/ci.yml
  src/gpg/1729F83938DA44E27BA0F4D3DBDB397470D12172.asc
  src/gpg/BFDDD28642824F8118EF77909B67A5C12229118F.asc
Labels: Dependencies
